{{- if and (.Values.secrets) (eq .Values.secretsEngine "kms") }}
apiVersion: secret.h3poteto.dev/v1beta1
kind: KMSSecret
metadata:
  name: {{ include "nd-common.fullname" . }}-secrets
spec:
  region: {{ .Values.kmsSecretsRegion }}
  encryptedData:
    {{- range $key, $value := .Values.secrets }}
    {{ $key | upper }}: {{ $value | quote }}
    {{- end }}
{{- end }}
