apiVersion: v2
name: prometheus-alerts
description: Helm Chart that provisions a series of common Prometheus Alerts
type: application
version: 0.2.1
appVersion: 0.0.1
maintainers:
  - name: diranged
    email: matt@nextdoor.com
