apiVersion: v2
name: daemonset-app
description: Default DaemonSet Helm Chart
type: application
version: 0.17.8
appVersion: latest
maintainers:
  - name: diranged
    email: matt@nextdoor.com
dependencies:
  - name: nd-common
    version: 0.5.4
    repository: file://../nd-common
