{{- /*
This template is used for local development.
*/}}
{{- if and (.Values.secrets) (eq .Values.secretsEngine "plaintext") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key | upper }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}